### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by thorn0** [jrit/web-resource-inliner#12]
Preparing pull requests, I wanted to use JSCS to automate checking and fixing the code style. However, it turned out there are different code styles in `src` (Allman-style blocks, jQuery-style parentheses) and in `test` (K&R blocks, parentheses without padding). So which one is more preferable? I'd like to unify the code style to make further contributing to the project easier.

**Comment by jrit** [comment]
Maybe just guess at what would be the least work to change and go from that. If you want to make style validation a requirement of `npm test` please feel free.

**Comment by thorn0** [comment]
It's exactly the same amount of work because it's JSCS (or maybe ESLint) that will format the code, not a human. So what I'm asking is which of the two styles we want to enforce.

**Comment by jrit** [comment]
If you are asking me to pick, use the one in `src`
