### ISSUE TITLE
Don't throw an error for cid: URLs

### ISSUE THREAD

**Issue by takkaria** [jrit/web-resource-inliner#21]
cid: URLs are used to reference attached images in emails.

**Current behaviour**
web-resource-inliner throws an error for cid: URLs.

**Expected behaviour**
Ignore cid: URLs in img tags.

**Comment by jrit** [comment]
Would this be resolved by ignoring `src` attributes when the value starts with `cid:`?

**Comment by takkaria** [comment]
I think that would work fine, yes.

**Comment by jrit** [comment]
should be fixed in https://github.com/jrit/web-resource-inliner/commit/eb84e0b12c5c62ec05bd09f1b2c8ae003ed73d1c with release coming soon
