### ISSUE TITLE
Bump DataUri package version to 1.0 to allow running inside Atom

### ISSUE THREAD

**Issue by iRyusa** [jrit/web-resource-inliner#26]
Hi there !

Datauri on 0.2 is based on `templayed` that use some evil `eval`, and it's not allowed inside Atom.

Datauri in 1.0 use regular ES6 template string instead of `templayed` ( https://github.com/heldr/datauri/blob/master/src/datauri/template/uri.js )

Thanks !

**Comment by jrit** [comment]
I just updated all the deps in master and plan to publish a release later today

**Comment by iRyusa** [comment]
Thanks ! :+1:
