### ISSUE TITLE
Request module

### ISSUE THREAD

**Issue by cexmmaqsood** [jrit/web-resource-inliner#32]
The dependency of this in package json allows new minor versions to be created. The request module has released a new minor version that upgrades one of their dependencies to ES6. This has caused our applications that don't support it to crash. Can the `^` be removed in the dependency for the `request` module?

**Comment by jrit** [comment]
Per mikeal (won't tag to avoid spamming him) this is as intended and he suggests how to handle. https://github.com/request/request/issues/2774
