### ISSUE TITLE
Error getting remote files to inline

### ISSUE THREAD

**Issue by tmcdonnell87** [jrit/web-resource-inliner#9]
It looks like you've lost the `relativeTo` param for remote file retrieval (https://github.com/jrit/web-resource-inliner/blob/master/src/util.js:149). 

I suggest making it similar to getTextReplacement (above):

```
if( util.isRemotePath( relativeTo ) )
{
    util.getRemote( url.resolve(relativeTo, src), callback, true );
}
```

Thanks!

**Comment by jrit** [comment]
@tmcdonnell87 it looks like you patched this in your fork, do you want to just open a pull request?

**Comment by tmcdonnell87** [comment]
Sorry, got sidetracked on a few things. Thanks for taking care of it.
